#!/usr/bin/env python3
"""Generates palette.json and palette.css from Source/Framework/ThemePalette.cs.

The C# file is the single source of truth for every theme's colors and fonts.
This script parses it with regex (no Roslyn/compiler available on Linux) and
fails LOUDLY (nonzero exit + message naming the missing member) rather than
emitting an incomplete palette — a silently-dropped color would drift the
design twin out of parity without anyone noticing.

Usage:  python3 devtools/design-twin/export_palette.py
Pure stdlib — no packages required.
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
THEME_FILE = REPO_ROOT / "Source" / "Framework" / "ThemePalette.cs"
OUT_JSON = Path(__file__).resolve().parent / "palette.json"
OUT_CSS = Path(__file__).resolve().parent / "palette.css"

# Order matches ThemePalette.All[] (the toolbar picker's display order).
THEME_ORDER = [
    "DarkMono", "DarkNavy", "LightClean", "LightWarm",
    "Stone", "Terra", "Sahara", "Obsidian",
]

# Color members, in the order they're written to ResourceDictionary by ApplyTo().
COLOR_MEMBERS = [
    "Bg", "PageBg", "Surface", "Raised", "SelectBg",
    "Border", "BorderMid",
    "Text", "TextSub", "TextDim",
    "Accent", "AccentDim",
    "Green", "GreenDim", "Red", "RedDim",
    "KnobOn", "KnobOff",
    "Swatch",
]

FONT_MEMBERS = ["MonoFont", "UiFont"]


def kebab(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def parse_block(theme_var, block):
    result = {"varName": theme_var}

    m = re.search(r'Name\s*=\s*"([^"]+)"', block)
    if not m:
        sys.exit(f"export_palette.py: theme '{theme_var}' has no Name = \"...\" — aborting")
    result["name"] = m.group(1)
    # id is derived from the DISPLAY name (Name = "..."), not the C# var name, so it
    # matches CaptureRunner.ToKebab(theme.Name) on the WPF side (they disagree for
    # Stone: var "Stone" vs display "Stone Gray" -> id must be "stone-gray").
    result["id"] = result["name"].lower().replace(" ", "-")

    colors = {}
    for member in COLOR_MEMBERS:
        m = re.search(rf'\b{member}\s*=\s*B\("(#[0-9a-fA-F]{{6,8}})"\)', block)
        if not m:
            sys.exit(f"export_palette.py: theme '{theme_var}' is missing color member '{member}' — aborting")
        colors[member] = m.group(1)
    result["colors"] = colors

    fonts = {}
    for member in FONT_MEMBERS:
        m = re.search(rf'\b{member}\s*=\s*new FontFamily\("([^"]+)"\)', block)
        if not m:
            sys.exit(f"export_palette.py: theme '{theme_var}' is missing font member '{member}' — aborting")
        fonts[member] = m.group(1)
    result["fonts"] = fonts

    return result


def main():
    if not THEME_FILE.exists():
        sys.exit(f"export_palette.py: cannot find {THEME_FILE}")
    src = THEME_FILE.read_text(encoding="utf-8")

    themes = []
    for var_name in THEME_ORDER:
        m = re.search(
            rf'public static readonly ThemePalette {var_name}\s*=\s*new ThemePalette\s*\{{(.*?)\}};',
            src, re.DOTALL,
        )
        if not m:
            sys.exit(f"export_palette.py: could not find theme block for '{var_name}' in {THEME_FILE} — aborting")
        themes.append(parse_block(var_name, m.group(1)))

    if len(themes) != len(THEME_ORDER):
        sys.exit(f"export_palette.py: expected {len(THEME_ORDER)} themes, parsed {len(themes)} — aborting")

    # ── palette.json ────────────────────────────────────────────────────────
    import json
    OUT_JSON.write_text(json.dumps({"themes": themes}, indent=2) + "\n", encoding="utf-8")

    # ── palette.css ─────────────────────────────────────────────────────────
    lines = [
        "/* AUTO-GENERATED by devtools/design-twin/export_palette.py",
        "   Source of truth: Source/Framework/ThemePalette.cs — do not hand-edit. */",
        "",
    ]
    for i, t in enumerate(themes):
        selector = f'html[data-theme="{t["id"]}"]'
        if i == 0:
            selector = f':root, html[data-theme="{t["id"]}"]'  # first theme (Dark Mono) is the default
        lines.append(f"{selector} {{")
        for member, hexval in t["colors"].items():
            lines.append(f"  --lemoine-{kebab(member)}: {hexval};")
        mono = t["fonts"]["MonoFont"].split(",")[0].strip()
        ui = t["fonts"]["UiFont"]
        lines.append(f'  --lemoine-mono-font: "{mono}", Consolas, monospace;')
        lines.append(f"  --lemoine-ui-font: {ui}, \"Segoe UI\", sans-serif;")
        lines.append("}")
        lines.append("")
    css_text = "\n".join(lines)
    OUT_CSS.write_text(css_text, encoding="utf-8")

    print(f"Wrote {OUT_JSON.relative_to(REPO_ROOT)} and {OUT_CSS.relative_to(REPO_ROOT)} "
          f"({len(themes)} themes, {len(COLOR_MEMBERS)} colors + {len(FONT_MEMBERS)} fonts each)")


if __name__ == "__main__":
    main()
